### ISSUE TITLE
Version 14.3.0

### ISSUE THREAD

**Issue by LoganGrier** [TheSpyder/rescript-nodejs#11]
Currently, the greatest version is 14.3.0 and the latest version is 14.2.1. Because of this, if a user sets their rescript-nodejs version to "^14.2.1", they will receive the older 14.3.0. 

Publishing the current head of main as version 14.3.1 to resolve this issue.

Also, I noticed that the change [here](https://github.com/TheSpyder/rescript-nodejs/pull/8) isn't backwards-compatible. Publishing the change as 14.3.0 from 14.2.0 violated [NPM's semantic versioning convention](https://docs.npmjs.com/about-semantic-versioning#incrementing-semantic-versions-in-published-packages).

**Comment by TheSpyder** [comment]
ugh. The problem with developing this library on two computers is sometimes I forget to push the version bumps. Thank you for pointing this out; I have published 14.3.1.

Semver is a bit weird when it comes to ReScript bindings. I am not creating any APIs myself, only helping others use NodeJS. As such that change was a bug fix; the `push` api did not match the underlying implementation and anyone attempting to use it would have had difficulty due to the lack of a return value.

I generally only bump the major version when adding API support for newer versions of NodeJS, and I haven't had time to do that since 16 was released.
